version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm

  webrunner:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
    volumes:
      - webrunner-logs:/app/logs
    command: ["python", "src/webrunner/main.py"]
    restart: "no"

volumes:
  webrunner-logs:


