[navconfig]
user-agent = "random"  # random false o un user-agent válido
proxy = "random" # random false o un proxy válido

[proxyconfig]
source = "geonode"  # sslproxies o geonode o spys
attempts = 5

[browserconfig]
type = "Chrome"
headless = true
disable-gpu = true
no-sandbox = true
enable-javascript = true
allow-insecure-localhost = true
ignore-certificate-errors = true
enable-automation = true
disable-dev-shm-usage = true
disable-blink-features = true

[navigatorconfig]
max-actions = 4
urls = [
    'https://tutorial-kopuru.streamlit.app/',
    'https://earthquakelocator.streamlit.app/',
    'https://stm-cv.streamlit.app/',
    #'https://kopuru-model-eval.streamlit.app/',
    #'https://litteragpt.streamlit.app/',
    'https://www.tejedormoreno.com/',
    'https://collatzeral.streamlit.app/',
    'https://graphicator.streamlit.app/',
    'https://talsa-mailing.streamlit.app/',
    'https://q2-pdf.streamlit.app/'
    ]
