name: Update README on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'  # Solo cuando haya cambias aqui

jobs:
  update_version:
    runs-on: ubuntu-latest  # Especifica en qué ambiente se ejecuta el job.
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # Asegúrate de que las credenciales persistan para el push.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --only dev
      - name: Update version in README
        run: poetry run python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README version" || echo "No changes to commit"
          git push

